### https://github.com/actions/upload-artifact
### https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
### https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
### https://github.com/r-lib/actions/tree/v2/setup-r-dependencies
### For uploading artifacts:
###     "path:" is the output path where Pandoc will write the compiled PDF. 
###      Note, this should be the same directory as the input paper.md
### For caching R packages:
###     cache-version - default 1. If you need to invalidate the existing cache 
###     pass any other number and a new cache will be used. Ignored if cache: false. 
###     Note that you can also delete caches manually.
name: Cache R packages

on: [push]

jobs:
  compile_data:
    runs-on: ubuntu-latest
    name: Process Data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: R Setup
        uses: |
          r-lib/actions/setup-r@v2
          r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::tidyverse
            any::openxlsx
        
      - name: Install packages
        run: | 
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("openxlsx")'
          Rscript -e 'install.packages("devtools")'
          