### https://github.com/actions/upload-artifact
### https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
### https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
### https://github.com/r-lib/actions/tree/v2/setup-r-dependencies
### https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
### https://github.com/marketplace/actions/download-workflow-artifact
### https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
### For uploading artifacts:
###     "path:" is the output path where Pandoc will write the compiled PDF. 
###      Note, this should be the same directory as the input paper.md
name: 2a. Test Main FrEDI Data

on: 
  workflow_dispatch:
    inputs:
      gen_test:
        type: choice
        description: Run general tests on main FrEDI data?
        required: true
        options:
        - no  
        - yes
      figures:
        type: choice
        description: Create scaled impact figures from main FrEDI data?
        required: true
        options:
        - no    
        - yes
      workflow_id:
        type: string
        description: Enter the run ID for the workflow from which to retrieve the main FrEDI Data
      fredi_branch:
        type: string
        description: Which FrEDI Package branch do you want to use?

jobs:
  compile_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    name: Process Data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # echo "$${{ github.ref_name }} ${{ inputs.workflow_id }} ${{ inputs.fredi_branch }} ${{ inputs.gen_test }} ${{ inputs.figures }}"
      - name: Send input status
        run: |
          echo "$${{ github.ref_name }} ${{ inputs.fredi_branch }} ${{ inputs.gen_test }} ${{ inputs.figures }}"  
      
      ### Download tmp_sysdata.rda from 1. Compile Main FrEDI Data run
      ### dawidd6/action-download-artifact@v7
      - name: Download artifact
        id:   download-artifact
        uses: actions/download-artifact@v4
        with: 
          github_token:    ${{secrets.GITHUB_TOKEN}}
          # workflow:        workflow_name.yml
          # workflow_search: false
          # workflow_conclusion: success
          # pr: ${{github.event.pull_request.number}}
          # commit: ${{github.event.pull_request.head.sha}}
          # branch: 
          ### Run ID
          # run-id: ${{ github.event.workflow_run.id }}
          # run_id: 1122334455
          run-id: ${{ inputs.workflow_id }}
          ### Optional, run number from the workflow
          # run_number: 34
          ### Optional, uploaded artifact name,
          ### will download all artifacts if not specified and extract them into respective subdirectories
          ### https://github.com/actions/download-artifact
          # name: artifact_name
          name_is_regexp: true
          ### Optional, a directory where to extract artifact(s), defaults to the current directory
          # path: extract_here
          path: ./data/
          if_no_artifact_found: fail
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 1
          packages: |
            any::tidyverse
            any::ggpubr
            any::openxlsx
            any::devtools
            any::admisc
            any::zoo


      - name: Install FrEDI
        run: |
          Rscript -e '
            devtools::install_github(
              repo         = "https://github.com/USEPA/FrEDI",
              ref          = "${{ github.event.inputs.fredi_branch }}",
              dependencies = FALSE,
              upgrade      = "never",
              force        = TRUE,
              type         = "source"
            )'

      - name: Run Tests on Main FrEDI Data
        run: |
          Rscript -e '
            ### Arguments
            doGenTests  <- "${{ inputs.gen_test }}" == "true" 
            doFigures   <- "${{ inputs.figures  }}" == "true"
            doTests     <- doGenTests | doFigures
            
            ### Directories for project, scripts, data, and artifacts
            projectDir  <- "."
            
            ### Create directory for outputs
            ### - Filename for general tests
            ### - Filename for list of tests
            outDir      <- projectDir |> file.path("data_tests")
            testFile    <- "configTestResults" |> paste0(".", "xlsx") 
            listFile    <- "testList" |> paste0(".", "R") 
            doOutDir    <- !(outDir |> dir.exists())
            if(doOutDir) outDir |> dir.create()
            
            ### Load Scripts
            scriptDir   <- projectDir |> file.path("scripts")
            scriptNames <- c("testFrediData") |> paste0(".", "R")
            scriptPaths <- scriptDir  |> file.path(scriptNames)
            # scriptDir |> file.path("testFrediData.R") |> source()
            for(path_i in scriptPaths){path_i |> source()}
            
            ### Load Data
            dataDir     <- projectDir |> file.path("data")
            artDir      <- dataDir    |> file.path("data")
            artName     <- "tmp_sysdata.rda" 
            artPath     <- artDir     |> file.path(artFile)
            artPath |> load()
            
            ### Run general test
            if(doTests) {
              testList <- projectDir |> testFrediData(
                dataList = rDataList , ### List with data (e.g., rDataList)
                general  = doGenTests, ### Whether to run the general test
                figures  = doFigures , ### Whether to create scaled impact figures
                save     = TRUE      ,
                outDir   = outDir    ,
                testFile = testFile
              ) ### End testFrediData
            } ### End if(doTests)
            testList |> save(file=listFile)
            "./data_tests/" |> list.files() |> print()
          '

      #  ./data_tests/*
      - name: Upload Tests
        uses: actions/upload-artifact@v4
        with:
          name: Data
          path: |
            ./data_tests/*


      # - name: Commit results
      #   run: |
      #     git config --local core.autocrlf false
      #     git config --local user.email "${{ github.actor }}@users.noreply.github.com"
      #     git config --local user.name  "${{ github.actor }}"
      #     git add data/tmp_sysdata.rd*
      #     git add data_tests/**.xlsx
      #     git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
      #     git commit -a -m "Updated temporary system data and tests"
      #     git push

