### https://github.com/actions/upload-artifact
### https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
### For uploading artifacts:
###     "path:" is the output path where Pandoc will write the compiled PDF. 
###      Note, this should be the same directory as the input paper.md
name: Compile main FrEDI Data
description: Compile and test main FrEDI data

on: [push]

jobs:
  compile_data:
    runs-on: ubuntu-latest
    name: Process Data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: R Setup
        uses: r-lib/actions/setup-r@v2
        
      - name: Install packages
        run: | 
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("openxlsx")'
          Rscript -e 'install.packages("devtools")'
          
      - name: Run createsystemData
        run: source("createsystemData_main.R")
        
      - name: Upload Tests
        uses: actions/upload-artifact@v3
        with:
          name: Data
          path: |
            ./data_tests/
            ./data/tmp_sysdata.rda
          
#      - name: Commit results
#        run: |
#          git config --local core.autocrlf false
#          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
#          git config --local user.name "${{ github.actor }}"
#          git add data/sysdata**
#          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
#          git commit -a -m "Compiled main FrEDI data"
#          git push 

