name: Render documents and upload

on:
  push:
    paths:
      - 'inst/extdata/**'

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: | 
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("openxlsx")'
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'install.packages("piggyback")'
      - name: Run createsystemData
        run: source("createsystemData.R")
      - name: Commit results
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add data/sysdata**
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit -a -m "update systemdata"
          git push 