### Overwrite FrEDI data with past data
name: Update FrEDI Data

# on: 
#   workflow_dispatch:
on:
  workflow_run:
    workflows: ["Compile FrEDI Data"]
    inputs:
      passed_tests:
        type: choice
        description: Did data pass tests?
        required: true
        options: 
        - no
        - yes
    

jobs:
  # This workflow contains a single job called "build"
  update_data:
    runs-on: ubuntu-latest
    name: Update Data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Send test status
        run: echo "${{ github.event.inputs.passed_tests }}"
        
      - name: Update Data
        if: |
          github.event.inputs.passed_tests == 'yes'
        run:  |
          Rscript -e '
            "./data" |> list.files() |> print()
            file0   <- "./data/tmp_sysdata.rda"
            file1   <- "./data/sysdata.rda"
            exists0 <- file0 |> file.exists()
            exists0 %>% print
            if(exists0){
              file.copy(from=file0, to=file1)
              file.remove(file0)
            }'

      - name: Add SV Data to sysdata
        if: |
          github.event.inputs.passed_tests == 'yes'
        run:  |
          Rscript -e 'source("./scripts/add_svData_to_sysdata.R")'
          
          
      - name: Commit results
        if: |
          github.event.inputs.passed_tests == 'yes'
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add data/sysdata**
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit -a -m "Compiled main FrEDI data"
          git push
