### Overwrite FrEDI data with past data
name: Compile SV Data

on: 
  workflow_dispatch:
    inputs:
      run_sv:
        type: choice
        description: Update SV proportions
        required: true
        options: 
        - no
        - yes
      run_formats:
        type: choice
        description: Update SV formatting table
        required: true
        options: 
        - no
        - yes
      run_pop:
        type: choice
        description: Update SV population projections
        required: true
        options: 
        - no
        - yes

jobs:
  compile_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    name: Process Data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Send input status
        run: |
          echo "${{ inputs.run_sv }} ${{ inputs.run_formats }} ${{ inputs.run_pop }}"
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 1
          packages: |
            any::tidyverse
            any::openxlsx
            any::devtools
      
      - name: Install FrEDI
        run: |
          Rscript -e 'devtools::install_github( 
              repo         = "https://github.com/USEPA/FrEDI", 
              ref          = "main", 
              subdir       = "FrEDI", 
              dependencies = FALSE,
              upgrade      = "never", 
              force        = TRUE,
              type         = "source" 
            )'
          
      - name: Configure SV data
        if: |
          inputs.run_sv      == 'yes' ||
          inputs.run_pop     == 'yes' ||
          inputs.run_formats == 'yes'

        run: |
          Rscript -e '
            source("./scripts/update_svDataObjects.R")
            fpath1      <- getwd()
            sv0         <- "${{ inputs.run_sv      }}" == "yes"
            pop0        <- "${{ inputs.run_pop     }}" == "yes"
            format0     <- "${{ inputs.run_formats }}" == "yes"
            list1       <- update_svDataObjects(
              fpath0  = fpath1,
              sv      = sv0,
              pop     = pop0,
              format  = format0,
              save    = TRUE,
              return  = TRUE
            )
            '

# x
#       - name: Commit results
#         if: |
#           github.event.inputs.run_sv == 'yes' ||
#           github.event.inputs.run_formats == 'yes' ||
#           github.event.inputs.run_pop == 'yes'
#         run: |
#           git config --local core.autocrlf false
#           git config --local user.email "${{ github.actor }}@users.noreply.github.com"
#           git config --local user.name "${{ github.actor }}"
#           git add data/sv/impactsLists/**.rda
#           git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
#           git commit -a -m "Updated SV FrEDI data objects"
#           git push
