### Overwrite FrEDI data with past data
name: Compile SV Data

on: 
  workflow_dispatch:
    inputs:
      update_svProps:
        type: choice
        description: Update SV proportions
        required: true
        options: no, yes
      update_svFormats:
        type: choice
        description: Update SV formatting table
        required: true
        options: no, yes
      update_svPop:
        type: choice
        description: Update SV population projections
        required: true
        options: no, yes

jobs:
  compile_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    name: Process Data
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Send input status
        run: |
          echo "${{ github.event.inputs.update_svProps }} \
            ${{ github.event.inputs.update_svFormats }} \
            ${{ github.event.inputs.update_svPop }}"
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 1
          packages: |
            any::tidyverse
            any::openxlsx
            any::devtools
      
      - name: Install FrEDI
        run: |
          Rscript -e 'devtools::install_github( 
              repo         = "https://github.com/USEPA/FrEDI", 
              ref          = "main", 
              subdir       = "FrEDI", 
              dependencies = FALSE,
              upgrade      = "never", 
              force        = TRUE,
              type         = "source" 
            )'
          
      - name: Configure SV data
        if: |
          github.event.inputs.update_svProps == 'yes' ||
          github.event.inputs.update_svFormats == 'yes' ||
          github.event.inputs.update_svPop == 'yes'
        run: |
          Rscript -e '
            source("./scripts/update_svDataObjects.R")
            fpath1      <- getwd()
            outPath1    <- fpath1 %>% file.path("data", "sv")
            list1       <- update_svDataObjects(
              fpath0  = ".",
              sv      = ${{ github.event.inputs.update_svProps }},
              pop     = ${{ github.event.inputs.update_svPop }},
              format  = ${{ github.event.inputs.update_svFormats }},
              save    = TRUE,
              return  = TRUE
            )
            '

# x
#       - name: Commit results
#         if: |
#           github.event.inputs.update_svProps == 'yes' ||
#           github.event.inputs.update_svFormats == 'yes' ||
#           github.event.inputs.update_svPop == 'yes'
#         run: |
#           git config --local core.autocrlf false
#           git config --local user.email "${{ github.actor }}@users.noreply.github.com"
#           git config --local user.name "${{ github.actor }}"
#           git add data/sv/impactsLists/**.rda
#           git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
#           git commit -a -m "Updated SV FrEDI data objects"
#           git push
